// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import { useState } from 'react';

import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import DrawIcon from '@mui/icons-material/Draw';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';

import { Markdown } from '@components/Markdown';

/**
 * Props accepted by the <PersonalityDialogAction> component.
 */
interface PersonalityDialogActionProps {
    /**
     * Generated personality (in Markdown) that was generated by AI.
     */
    personality: string;
}

/**
 * The <PersonalityDialogAction> shows an action that can open a dialog to make the generated
 * writing personalities and styles inspectable through the user interface.
 */
export function PersonalityDialogAction(props: PersonalityDialogActionProps) {
    const [ open, setOpen ] = useState<boolean>(false);

    return (
        <>
            <Tooltip title="Generated personality…">
                <IconButton size="small" onClick={ () => setOpen(true) }>
                    <DrawIcon fontSize="inherit" />
                </IconButton>
            </Tooltip>
            { !!open &&
                <Dialog open={!!open} onClose={ () => setOpen(false) } fullWidth>
                    <DialogTitle>
                        Generated writing personality…
                    </DialogTitle>
                    <DialogContent>
                        <Markdown>{props.personality}</Markdown>
                    </DialogContent>
                    <DialogActions sx={{ pt: 0, mr: 2, mb: 2 }}>
                        <Button onClick={ () => setOpen(false) } variant="text">
                            Close
                        </Button>
                    </DialogActions>
                </Dialog> }
        </>
    );
}
