// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import { useCallback, useState } from 'react';

import Button from '@mui/material/Button';
import Collapse from '@mui/material/Collapse';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Divider from '@mui/material/Divider';

import { CommunicationLanguageView, type CommunicationLanguage } from './CommunicationLanguageView';
import { CommunicationMessageView } from './CommunicationMessageView';

/**
 * Props accepted by the <CommunicationDialog> component.
 */
export interface CommunicationDialogProps {
    /**
     * Callback to invoke when the dialog should be closed.
     */
    onClose: () => void;

    /**
     * Whether the dialog should be opened and presented to the user.
     */
    open: boolean;

    // TODO: preferredLanguage (skip the language step)

    /**
     * Dialog title.
     */
    title: string;
}

/**
 * The <CommunicationDialog> will include a dialog that allows an e-mail to be generated by AI and
 * sent to a volunteer on behalf of the signed in user. A server action must be provided to commit
 * the action this dialog exists for.
 */
export function CommunicationDialog(props: React.PropsWithChildren<CommunicationDialogProps>) {
    const { onClose, open, title } = props;

    const [ step, setStep ] = useState<'language' | 'message' | 'confirmation'>('message');

    const handleLanguageSelected = useCallback(async (language: CommunicationLanguage) => {
        await new Promise(resolve => setTimeout(resolve, 1500));
        throw new Error('Not implemented yet');
    }, []);

    const handleRefresh = useCallback(async () => {
        await new Promise(resolve => setTimeout(resolve, 1500));
        throw new Error('Not implemented yet');
    }, []);

    return (
        <Dialog onClose={onClose} open={open} fullWidth>
            <DialogTitle>
                {title}
            </DialogTitle>
            { !!props.children &&
                <>
                    <DialogContent sx={{ marginY: -1 }}>
                        {props.children}
                    </DialogContent>
                    <Divider />
                </> }
            <DialogContent sx={{ overflowY: 'visible', paddingY: 2 }}>
                <Collapse in={ step === 'language' } mountOnEnter unmountOnExit>
                    <CommunicationLanguageView onLanguageSelected={handleLanguageSelected} />
                </Collapse>
                <Collapse in={ step === 'message' } mountOnEnter unmountOnExit>
                    <CommunicationMessageView onRefresh={handleRefresh} />
                </Collapse>
            </DialogContent>
            <Divider />
            <DialogActions sx={{ pt: 1, mr: 1, mb: 0 }}>
                <Button onClick={onClose} variant="text">Close</Button>
            </DialogActions>
        </Dialog>
    );
}
