// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import { useCallback, useState } from 'react';

import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import CheckIcon from '@mui/icons-material/Check';
import Collapse from '@mui/material/Collapse';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Divider from '@mui/material/Divider';
import SendIcon from '@mui/icons-material/Send';

import type { CommunicationPromptId } from '@lib/ai/PromptFactory';
import type { Language } from '@lib/ai/Language';
import { CommunicationConfirmSilentView } from './CommunicationConfirmSilentView';
import { CommunicationConfirmationView } from './CommunicationConfirmationView';
import { CommunicationLanguageView, type CommunicationLanguage } from './CommunicationLanguageView';
import { CommunicationMessageView } from './CommunicationMessageView';
import { type TypedPromptData, executeCommunicationPrompt } from '@lib/ai/Actions';

/**
 * State that the <CommunicationDialog> can be in.
 */
type CommunicationDialogState = 'language' | 'confirmSilent' | 'message' | 'confirmation';

/**
 * Props accepted by the <CommunicationDialog> component.
 */
export interface CommunicationDialogProps<T extends CommunicationPromptId> {
    /**
     * Whether the silent communication option should be disabled.
     */
    disableSilent?: boolean;

    /**
     * Language in which the communication should be written, when known.
     */
    language?: CommunicationLanguage;

    /**
     * Callback to invoke when the dialog should be closed.
     */
    onClose: () => void;

    /**
     * Whether the dialog should be opened and presented to the user.
     */
    open: boolean;

    /**
     * Unique ID of the prompt that should be executed to generate the message.
     */
    promptId: T;

    /**
     * Parameters expected by the prompt that should be executed to generate the message.
     */
    promptParams: TypedPromptData<T>;

    /**
     * Unique ID of the user who this communication will be directed to.
     */
    recipientId: number;

    /**
     * Dialog title.
     */
    title: string;
}

/**
 * The <CommunicationDialog> will include a dialog that allows an e-mail to be generated by AI and
 * sent to a volunteer on behalf of the signed in user. A server action must be provided to commit
 * the action this dialog exists for.
 *
 * Functionally, the communication dialog exposes a multi-step process towards easily sending an
 * e-mail to one of our volunteers, with multiple possible outcomes.
 *
 *   1. Language selection. Dutch and English are available by default, and certain users may have
 *      sufficient permission to commit "Silent" actions. When known, the preferred language of the
 *      volunteer may be highlighted.
 *
 *   2a. For written communication, an AI-generated message will be shown in the selected language.
 *       Both the message and subject line may be edited, as we want humans to remain in control of
 *       our outwards communication.
 *
 *   2b. For silent communication, a confirmation will be requested that this really is the user's
 *       intention. It means that something meaningful changes about their participation without
 *       letting them know in a written forum. That may be ok.
 *
 *   3. Confirmation that the selected action has completed. This will only be shown after the given
 *      server action for committing this dialog has successfully been executed.
 *
 * Each step of the dialog gracefully handles errors by showing them to the user. They may not
 * always be immediately actionable, but they should be clear enough for a proper bug report.
 *
 * @todo Provide a decent responsive behaviour for mobile devices
 */
export function CommunicationDialog<T extends CommunicationPromptId>(
    props: React.PropsWithChildren<CommunicationDialogProps<T>>)
{
    const { onClose, open, title } = props;

    const [ dialogState, setDialogState ] = useState<CommunicationDialogState>('language');

    const [ selectedLanguage, setSelectedLanguage ] = useState<Language | undefined>();

    const [ generatedMessage, setGeneratedMessage ] = useState<string | undefined>();
    const [ generatedSubject, setGeneratedSubject ] = useState<string | undefined>();

    const [ confirmationMessage, setConfirmationMessage ] = useState<string | undefined>();

    const [ commitLoading, setCommitLoading ] = useState<boolean>(false);

    // ---------------------------------------------------------------------------------------------
    // Machinery to invoke the Server Action to obtain the response from the server. The state will
    // be advanced in order to display the generated message automatically once completed.
    // ---------------------------------------------------------------------------------------------

    const doExecuteCommunicationPrompt = useCallback(async (language: Language) => {
        const response = await executeCommunicationPrompt(
            props.promptId, props.recipientId, language, props.promptParams);

        if (!response.success)
            throw new Error(response.error);

        setGeneratedMessage(response.message);
        setGeneratedSubject(response.subject);

        setDialogState('message');

    }, [ props.promptId, props.promptParams, props.recipientId ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "language" state:
    // ---------------------------------------------------------------------------------------------

    const handleLanguageSelected = useCallback(async (language: CommunicationLanguage) => {
        switch (language) {
            case 'Dutch':
            case 'English':
                setSelectedLanguage(language);

                await doExecuteCommunicationPrompt(language);
                break;

            case 'Silent':
                setGeneratedMessage(undefined);
                setGeneratedSubject(undefined);

                setDialogState('confirmSilent');
                break
        }

    }, [ doExecuteCommunicationPrompt ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "confirmSilent" state:
    // ---------------------------------------------------------------------------------------------

    const handleCommitAction = useCallback(async () => {
        setCommitLoading(true);

        // TODO: Implement this.
        await new Promise(resolve => setTimeout(resolve, 2000));

        setCommitLoading(false);
        setConfirmationMessage('Not yet implemented');

        setDialogState('confirmation');

    }, [ /* no deps */ ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "message" state:
    // ---------------------------------------------------------------------------------------------

    const handleBackToLanguageSelection = useCallback(() => {
        setDialogState('language');
    }, []);

    const handleRefreshMessage = useCallback(async () => {
        if (!!selectedLanguage)
            await doExecuteCommunicationPrompt(selectedLanguage);

    }, [ doExecuteCommunicationPrompt, selectedLanguage ]);

    // ---------------------------------------------------------------------------------------------

    return (
        <Dialog onClose={onClose} open={open} fullWidth>
            <DialogTitle>
                {title}
            </DialogTitle>
            { !!props.children &&
                <>
                    <DialogContent sx={{ marginY: -1 }}>
                        {props.children}
                    </DialogContent>
                    <Divider />
                </> }
            <DialogContent sx={{ overflowY: 'visible', paddingY: 2 }}>
                <Collapse in={ dialogState === 'language' } mountOnEnter unmountOnExit>
                    <CommunicationLanguageView disableSilent={props.disableSilent}
                                               language={props.language}
                                               onLanguageSelected={handleLanguageSelected} />
                </Collapse>
                <Collapse in={ dialogState === 'confirmSilent' } mountOnEnter unmountOnExit>
                    <CommunicationConfirmSilentView />
                </Collapse>
                <Collapse in={ dialogState === 'message' } mountOnEnter unmountOnExit>
                    <CommunicationMessageView message={generatedMessage} subject={generatedSubject}
                                              onRefresh={handleRefreshMessage} />
                </Collapse>
                <Collapse in={ dialogState === 'confirmation' } mountOnEnter unmountOnExit>
                    <CommunicationConfirmationView message={confirmationMessage!} />
                </Collapse>
            </DialogContent>
            <Divider />
            <DialogActions sx={{ pt: 1, mr: 1, ml: 1.5, mb: 0 }}>
                <Box sx={{ flexGrow: 1 }}>
                    <Collapse in={ dialogState === 'message' || dialogState === 'confirmSilent' }
                              orientation="horizontal">
                        <Button onClick={handleBackToLanguageSelection} variant="text"
                                startIcon={<ArrowBackIcon />}>
                            Back
                        </Button>
                    </Collapse>
                </Box>
                <Button onClick={onClose} variant="text">
                    { dialogState === 'confirmation' ? 'Close' : 'Cancel' }
                </Button>
                <Collapse in={ dialogState === 'message' } orientation="horizontal">
                    <Button variant="contained" color="primary" onClick={handleCommitAction}
                            endIcon={ <SendIcon /> } loading={commitLoading}>
                        Send
                    </Button>
                </Collapse>
                <Collapse in={ dialogState === 'confirmSilent' } orientation="horizontal">
                    <Button variant="contained" color="primary" onClick={handleCommitAction}
                            endIcon={ <CheckIcon /> } loading={commitLoading}>
                        Continue
                    </Button>
                </Collapse>
            </DialogActions>
        </Dialog>
    );
}
