// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import { useCallback, useEffect, useState } from 'react';

import Alert from '@mui/material/Alert';
import Collapse from '@mui/material/Collapse';
import IconButton from '@mui/material/IconButton';
import RefreshIcon from '@mui/icons-material/Refresh';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Tooltip from '@mui/material/Tooltip';

/**
 * Props accepted by the <CommunicationMessageView> component.
 */
interface CommunicationMessageViewProps {
    /**
     * Body of the message.
     */
    message?: string;

    /**
     * Callback to be invoked when the user wants to generate another message.
     */
    onRefresh: () => Promise<void>;

    /**
     * Subject line for the message.
     */
    subject?: string;
}

/**
 * The <CommunicationMessageView> component enables the user to change the proposed message that was
 * generated by AI. We care about people always remaining in control of the experience.
 *
 * Both input fields are uncontrolled, which means that a React state update will be enqueued every
 * time the value of a field changes. This could likely be optimised, but we've chosen in favour of
 * simplicity for now.
 */
export function CommunicationMessageView(props: CommunicationMessageViewProps) {
    const [ message, setMessage ] = useState<string>(props.message || '');
    const [ subject, setSubject ] = useState<string>(props.subject || '');

    // ---------------------------------------------------------------------------------------------
    // Handles changes to the subject and message that were made by the user, which are uncontrolled
    // components. Also observe changes to the received props, to reflect refreshed values.
    // ---------------------------------------------------------------------------------------------

    const handleMessageChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
        setMessage(event.target.value);
    }, [ /* no deps */ ]);

    const handleSubjectChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
        setSubject(event.target.value);
    }, [ /* no deps */ ]);

    useEffect(() => {
        setMessage(props.message || '');
        setSubject(props.subject || '');

    }, [ props.message, props.subject ]);

    // ---------------------------------------------------------------------------------------------
    // Ability to refresh the generated message in case the author does not like the output. There
    // is no limit to the amount of refreshes that can be generated.
    // ---------------------------------------------------------------------------------------------

    const [ refreshError, setRefreshError ] = useState<string | undefined>();
    const [ refreshErrorOpen, setRefreshErrorOpen ] = useState<boolean>(false);
    const [ refreshing, setRefreshing ] = useState<boolean>(false);

    const handleRefresh = useCallback(async () => {
        setRefreshErrorOpen(false);
        setRefreshing(true);
        try {
            await props.onRefresh();
        } catch (error: any) {
            setRefreshErrorOpen(true);
            setRefreshError(error.message);
        } finally {
            setRefreshing(false);
        }
    }, [ props.onRefresh ]);

    // ---------------------------------------------------------------------------------------------

    return (
        <>
            <Stack direction="column" spacing={2}>
                <Stack direction="row" spacing={1} sx={{ alignItems: 'center', pr: 1 }}>
                    <TextField label="Subject" fullWidth size="small" disabled={refreshing}
                               value={subject} onChange={handleSubjectChange} />
                    <Tooltip title="Generate a new message">
                        <IconButton onClick={handleRefresh} loading={refreshing} size="small">
                            <RefreshIcon color="primary" fontSize="small" sx={{
                                visibility: refreshing ? 'hidden' : 'visible',
                            }} />
                        </IconButton>
                    </Tooltip>
                </Stack>
                <TextField label="Message" fullWidth size="small" multiline disabled={refreshing}
                           value={message} onChange={handleMessageChange} />
            </Stack>
            <Collapse in={!!refreshErrorOpen}>
                <Alert severity="error" sx={{ mt: 2 }}>
                    {refreshError}
                </Alert>
            </Collapse>
        </>
    );
}
