// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import { useCallback, useContext, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

import Alert from '@mui/material/Alert';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import Button from '@mui/material/Button';
import CheckIcon from '@mui/icons-material/Check';
import Collapse from '@mui/material/Collapse';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Divider from '@mui/material/Divider';
import SendIcon from '@mui/icons-material/Send';
import Stack from '@mui/material/Stack';

import type { CommunicationPromptId } from '@lib/ai/PromptFactory';
import type { Language } from '@lib/ai/Language';
import type { ServerActionResult } from '@lib/serverAction';
import { AdminClientContext } from '@app/admin/AdminClientContext';
import { CommunicationConfirmSilentView } from './CommunicationConfirmSilentView';
import { CommunicationConfirmationView } from './CommunicationConfirmationView';
import { CommunicationLanguageView, type CommunicationLanguage } from './CommunicationLanguageView';
import { CommunicationMessageView } from './CommunicationMessageView';
import { CommunicationPromptSelectionView, type CommunicationSelectionPrompt } from './CommunicationPromptSelectionView';
import { type TypedPromptData, executeCommunicationPrompt } from '@lib/ai/Actions';

/**
 * State that the <CommunicationDialog> can be in.
 */
type CommunicationDialogState =
    'prompt' | 'language' | 'confirmSilent' | 'message' | 'confirmation';

/**
 * Base props accepted by the <CommunicationDialog> component.
 */
interface BaseCommunicationDialogProps {
    /**
     * Whether the silent communication option should be disabled.
     */
    disableSilent?: boolean;

    /**
     * Language in which the communication should be written, when known.
     */
    language?: CommunicationLanguage;

    /**
     * Callback to invoke when the dialog should be closed.
     */
    onClose: () => void;

    /**
     * Whether the dialog should be opened and presented to the user.
     */
    open: boolean;

    /**
     * Unique ID of the user who this communication will be directed to.
     */
    recipientId: number;

    /**
     * Dialog title.
     */
    title: string;
}

/**
 * Props accepted by the <CommunicationDialog> component.
 */
export type CommunicationDialogProps<T extends CommunicationPromptId = CommunicationPromptId> =
    BaseCommunicationDialogProps & (
        | {
              /**
               * Server Action to invoke when the action is ready to be committed.
               */
              action: (subject?: string, message?: string) => Promise<ServerActionResult>;

              /**
               * Unique ID of the prompt that should be executed to generate the message.
               */
              promptId: T;

              /**
               * Parameters expected by the prompt that should be executed to generate the message.
               */
              promptParams: TypedPromptData<T>;

              /**
               * An array containing one or more prompts this dialog can handle.
               */
              prompts?: never;
          }
        | {
              /**
               * Server Action to invoke when the action is ready to be committed.
               */
              action: (promptId: CommunicationPromptId, subject?: string, message?: string)
                  => Promise<ServerActionResult>;

              /**
               * Unique ID of the prompt that should be executed to generate the message.
               */
              promptId?: never;

              /**
               * Parameters expected by the prompt that should be executed to generate the message.
               */
              promptParams?: never;

              /**
               * An array containing one or more prompts this dialog can handle.
               */
              prompts: {
                  [K in CommunicationPromptId]: CommunicationSelectionPrompt & {
                      /**
                       * Unique ID of the prompt that should be executed to generate the message.
                       */
                      promptId: K;

                      /**
                       * Parameters expected by the prompt that should be executed to generate the
                       * message.
                       */
                      promptParams: TypedPromptData<K>;
                  };
              }[CommunicationPromptId][];
          }
    );

/**
 * The <CommunicationDialog> will include a dialog that allows an e-mail to be generated by AI and
 * sent to a volunteer on behalf of the signed in user. A server action must be provided to commit
 * the action this dialog exists for.
 *
 * Functionally, the communication dialog exposes a multi-step process towards easily sending an
 * e-mail to one of our volunteers, with multiple possible outcomes.
 *
 *   1.  Prompt selection. It's possible for the <CommunicationDialog> to host multiple prompts, in
 *       which case the user will be presented with a prompt selection interface first.
 *
 *   2.  Language selection. Dutch and English are available by default, and certain users may have
 *       sufficient permission to commit "Silent" actions. When known, the preferred language of the
 *       volunteer may be highlighted.
 *
 *   3a. For written communication, an AI-generated message will be shown in the selected language.
 *       Both the message and subject line may be edited, as we want humans to remain in control of
 *       our outwards communication.
 *
 *   3b. For silent communication, a confirmation will be requested that this really is the user's
 *       intention. It means that something meaningful changes about their participation without
 *       letting them know in a written forum. That may be ok.
 *
 *   4.  Confirmation that the selected action has completed. This will only be shown after the
 *       given server action for committing this dialog has successfully been executed.
 *
 * Each step of the dialog gracefully handles errors by showing them to the user. They may not
 * always be immediately actionable, but they should be clear enough for a proper bug report.
 */
export function CommunicationDialog<T extends CommunicationPromptId = CommunicationPromptId>(
    props: React.PropsWithChildren<CommunicationDialogProps<T>>)
{
    const { allowSilentMutations, isMobile } = useContext(AdminClientContext);

    const router = useRouter();
    const prompts = useMemo(() => {
        return props.prompts ?? [
            {
                promptId: props.promptId,
                promptParams: props.promptParams,
            }
        ];
    }, [ props.promptId, props.promptParams, props.prompts ]);

    const [ errorOpen, setErrorOpen ] = useState<boolean>(false);
    const [ error, setError ] = useState<string | undefined>();

    const [ selectedPromptId, setSelectedPromptId ] = useState<CommunicationPromptId | undefined>(
        () => prompts.length === 1 ? prompts[0].promptId : undefined);

    const [ dialogTitle, setDialogTitle ] = useState<string>(props.title);
    const [ dialogState, setDialogState ] = useState<CommunicationDialogState>(
        () => prompts.length === 1 ? 'language' : 'prompt');

    const [ selectedLanguage, setSelectedLanguage ] = useState<Language | undefined>();

    const [ generatedMessage, setGeneratedMessage ] = useState<string | undefined>();
    const [ generatedSubject, setGeneratedSubject ] = useState<string | undefined>();

    const [ confirmationMessage, setConfirmationMessage ] = useState<string | undefined>();

    const [ commitLoading, setCommitLoading ] = useState<boolean>(false);

    // ---------------------------------------------------------------------------------------------
    // Machinery to invoke the Server Action to obtain the response from the server. The state will
    // be advanced in order to display the generated message automatically once completed.
    // ---------------------------------------------------------------------------------------------

    const doExecuteCommunicationPrompt = useCallback(async (language: Language) => {
        if (!selectedPromptId)
            throw new Error('No prompt has been selected for execution');

        const selectedPromptParams =
            prompts.find(prompt => prompt.promptId === selectedPromptId)?.promptParams;
        if (!selectedPromptParams)
            throw new Error('No parameters can be found for the selected prompt');

        const response = await executeCommunicationPrompt(
            selectedPromptId, props.recipientId, language, selectedPromptParams);

        if (!response.success)
            throw new Error(response.error);

        setGeneratedMessage(response.message);
        setGeneratedSubject(response.subject);

        setDialogState('message');

    }, [ prompts, props.recipientId, selectedPromptId ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "prompt" state:
    // ---------------------------------------------------------------------------------------------

    const handlePromptSelected = useCallback((promptId: CommunicationPromptId) => {
        setSelectedPromptId(promptId);
        for (const prompt of prompts) {
            if (prompt.promptId === promptId && 'title' in prompt)
                setDialogTitle(prompt.title!);
        }

        setDialogState('language');

    }, [ prompts]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "language" state:
    // ---------------------------------------------------------------------------------------------

    const handleLanguageSelected = useCallback(async (language: CommunicationLanguage) => {
        switch (language) {
            case 'Dutch':
            case 'English':
                setSelectedLanguage(language);

                await doExecuteCommunicationPrompt(language);
                break;

            case 'Silent':
                setGeneratedMessage(undefined);
                setGeneratedSubject(undefined);

                setDialogState('confirmSilent');
                break
        }

    }, [ doExecuteCommunicationPrompt ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "confirmSilent" state:
    // ---------------------------------------------------------------------------------------------

    const handleCommitAction = useCallback(async () => {
        setCommitLoading(true);
        setErrorOpen(false);

        try {
            let response: Awaited<ReturnType<CommunicationDialogProps<T>['action']>>;
            if (!!props.prompts)
                response = await props.action(selectedPromptId!, generatedSubject, generatedMessage);
            else
                response = await props.action(generatedSubject, generatedMessage);

            if (!response.success)
                throw new Error(response.error);

            if (response.refresh)
                router.refresh();

            if (response.redirect) {
                router.push(response.redirect);
            } else if (response.close) {
                props.onClose();
            } else {
                setConfirmationMessage(response.message);
                setDialogState('confirmation');
            }
        } catch (error: any) {
            setError(error.message);
            setErrorOpen(true);
        } finally {
            setCommitLoading(false);
        }
    }, [ generatedMessage, generatedSubject, props.action, props.onClose, props.prompts, router,
         selectedPromptId
     ]);

    // ---------------------------------------------------------------------------------------------
    // Callbacks for the "language" and "message" states:
    // ---------------------------------------------------------------------------------------------

    const handleBackToPromptSelection = useCallback(() => {
        setDialogTitle(props.title);
        setDialogState('prompt');
    }, [ props.title ]);

    const handleBackToLanguageSelection = useCallback(() => {
        setDialogState('language');
        setErrorOpen(false);
    }, []);

    const handleRefreshMessage = useCallback(async () => {
        if (!!selectedLanguage)
            await doExecuteCommunicationPrompt(selectedLanguage);

    }, [ doExecuteCommunicationPrompt, selectedLanguage ]);

    // ---------------------------------------------------------------------------------------------

    return (
        <Dialog onClose={props.onClose} open={props.open} fullWidth>
            <DialogTitle>
                {dialogTitle}
            </DialogTitle>
            { !!props.children &&
                <>
                    <DialogContent sx={{ marginY: -1 }}>
                        {props.children}
                    </DialogContent>
                    <Divider />
                </> }
            <DialogContent sx={{ overflowY: 'visible', paddingY: 2 }}>
                <Collapse in={ dialogState === 'prompt' } mountOnEnter unmountOnExit>
                    <CommunicationPromptSelectionView onPromptSelected={handlePromptSelected}
                                                      prompts={prompts} />
                </Collapse>
                <Collapse in={ dialogState === 'language' } mountOnEnter unmountOnExit>
                    <CommunicationLanguageView allowSilentMutations={allowSilentMutations}
                                               disableSilent={props.disableSilent}
                                               isMobile={isMobile}
                                               language={props.language}
                                               onLanguageSelected={handleLanguageSelected} />
                </Collapse>
                <Collapse in={ dialogState === 'confirmSilent' } mountOnEnter unmountOnExit>
                    <CommunicationConfirmSilentView />
                </Collapse>
                <Collapse in={ dialogState === 'message' } mountOnEnter unmountOnExit>
                    <CommunicationMessageView message={generatedMessage} subject={generatedSubject}
                                              onChangeMessage={setGeneratedMessage}
                                              onChangeSubject={setGeneratedSubject}
                                              onRefresh={handleRefreshMessage} />
                </Collapse>
                <Collapse in={ dialogState === 'confirmation' } mountOnEnter unmountOnExit>
                    <CommunicationConfirmationView message={confirmationMessage!} />
                </Collapse>
                <Collapse in={errorOpen}>
                    <Alert severity="error" sx={{ mt: 2 }}>
                        {error}
                    </Alert>
                </Collapse>
            </DialogContent>
            <Divider />
            <DialogActions sx={{ pt: 1, mr: 1, ml: 1.5, mb: 0 }}>
                <Stack direction="row" sx={{ flexGrow: 1 }}>
                    <Collapse in={ dialogState === 'language' && prompts.length > 1 }
                              orientation="horizontal">
                        <Button onClick={handleBackToPromptSelection} variant="text"
                                startIcon={<ArrowBackIcon />}>
                            Back
                        </Button>
                    </Collapse>
                    <Collapse in={ dialogState === 'message' || dialogState === 'confirmSilent' }
                              orientation="horizontal">
                        <Button onClick={handleBackToLanguageSelection} variant="text"
                                startIcon={<ArrowBackIcon />}>
                            Back
                        </Button>
                    </Collapse>
                </Stack>
                <Button onClick={props.onClose} variant="text">
                    { dialogState === 'confirmation' ? 'Close' : 'Cancel' }
                </Button>
                <Collapse in={ dialogState === 'message' } orientation="horizontal">
                    <Button variant="contained" color="primary" onClick={handleCommitAction}
                            endIcon={ <SendIcon /> } loading={commitLoading}>
                        Send
                    </Button>
                </Collapse>
                <Collapse in={ dialogState === 'confirmSilent' } orientation="horizontal">
                    <Button variant="contained" color="primary" onClick={handleCommitAction}
                            endIcon={ <CheckIcon /> } loading={commitLoading}>
                        Continue
                    </Button>
                </Collapse>
            </DialogActions>
        </Dialog>
    );
}
