// Copyright 2025 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

import { type GenerateContentParameters, type GoogleGenAIOptions, type Part, GoogleGenAI, ThinkingLevel } from '@google/genai';

import type { AiSupportedModel } from './Models';

/**
 * Variant of the Gemini API to use when interacting with the service.
 */
export type GeminiApi = 'Gemini' | 'GeminiEnterprise';

/**
 * Complexity levels for text generation that's expected to be available within configuration, and
 * can be picked when executing a `generateText()` query.
 */
export type TextGenerationComplexity = 'low' | 'medium' | 'high';

/**
 * Level of reasoning that the model should apply when generating text.
 */
export type TextGenerationThinkingLevel = 'minimal' | 'low' | 'medium' | 'high';

/**
 * Settings accepted by the GenAI client.
 */
export interface ClientSettings {
    /**
     * Variant of the Gemini API to use.
     */
    api: GeminiApi;

    /**
     * Google Cloud API key that should be used for generative AI.
     */
    apiKey: string;

    /**
     * Options to consider when the Gemini Enterprise API is being used.
     */
    googleCloud: {
        /**
         * Credentials that should be used when authenticating.
         */
        credentials: string;

        /**
         * Location from which the API should be consumed, if any.
         */
        location?: string;

        /**
         * Google Cloud Project ID.
         */
        project: string;
    };

    /**
     * Model selection controlling which models should be used for different use cases.
     */
    models: {
        /**
         * Model to use when generating images.
         */
        image: AiSupportedModel;

        /**
         * Model to use when generating text.
         */
        text: { [k in TextGenerationComplexity]: AiSupportedModel };
    };

    /**
     * Quality settings that apply to text prompts, including variability of the output.
     */
    quality: {
        /**
         * Value that controls the degree of randomness in token selection. Lower temperatures are good
         * for prompts that require a less open-ended or creative response, while higher temperatures
         * can lead to more diverse or creative results.
         */
        temperature?: number;

        /**
         * Tokens are selected from the most to least probable until the sum of their probabilities
         * equals this value.
         */
        topP?: number;

        /**
         * Thinking level that significantly improves the model's reasoning and multi-step planning
         * abilities. Higher levels are useful for complex reasoning, but will take longer to
         * generate.
         *
         * @see https://ai.google.dev/gemini-api/docs/thinking
         * @default "medium"
         */
        thinkingLevel?: TextGenerationThinkingLevel;
    };
};

/**
 * Subset of the total model response information that captures the result of a request.
 */
type ModelResponse<T extends object> =
    { success: false, error: string } | ({
        /**
         * Boolean indicating that a response could be generated.
         */
        success: true;

        /**
         * Unique ID of the response generated by the model, owned by the provider.
         */
        responseId?: string;

    } & T);

/**
 * Information returned by the model upon execution of a image prompt.
 */
export type ModelImageResponse = ModelResponse<{
    /**
     * Byte data returned by the model, as a base64-encoded PNG. Guaranteed to exist.
     */
    data: string;

    /**
     * Textual output of the model in addition to the image data. Not guaranteed to exist.
     */
    text?: string;
}>;

/**
 * Information returned by the model upon execution of a text prompt.
 */
export type ModelTextResponse = ModelResponse<{
    /**
     * Textual output of the model. Guaranteed to exist.
     */
    text: string;
}>;

/**
 * Parameters that can be passed when requesting a model.
 */
interface GenerateRequest {
    /**
     * One or more attachments that should be included with the prompt. Use raw byte data, and make
     * sure that the right mime type is set on the entry.
     */
    attachments?: {
        /**
         * Source data, as raw, unencoded bytes. Will be encoded as required by the client.
         */
        bytes: Uint8Array<ArrayBuffer> | Promise<Uint8Array<ArrayBuffer>>;

        /**
         * The IANA standard MIME type of the source data.
         */
        mimeType: string;

    }[];

    /**
     * The prompt that explains to the model what it's supposed to do. (Required.)
     */
    prompt: string;

    /**
     * System prompt, explaining to the model what it is.
     */
    systemPrompt?: string;
}

/**
 * Parameters that can be passed when requesting a model to generate an image.
 */
interface GenerateImageRequest extends GenerateRequest {
    /**
     * Aspect ratio of the image that should be generated.
     */
    aspectRatio: '1:1' | '2:3' | '3:2' | '3:4' | '4:3' | '9:16' | '16:9' | '21:9';
}

/**
 * Parameters that can be passed when requesting a model to generate text.
 */
interface GenerateTextRequest extends GenerateRequest {
    /**
     * Complexity of the query, which helps define the specific model to use.
     * @default "medium"
     */
    complexity?: TextGenerationComplexity;

    /**
     * Thinking level that significantly improves the model's reasoning and multi-step planning
     * abilities. Higher levels are useful for complex reasoning, but will take longer to generate.
     *
     * @see https://ai.google.dev/gemini-api/docs/thinking
     * @default `ClientSettings.quality.thinkingLevel`
     */
    thinkingLevel?: TextGenerationThinkingLevel;
}

/**
 * Client to the Google Gen AI SDK for TypeScript and JavaScript, through which new Gemini features
 * will consistently be exposed. Can switch between the VertexAI and Google AI Studio backends.
 * 
 * @see https://googleapis.github.io/js-genai/release_docs/index.html
 * @see https://www.npmjs.com/package/@google/genai
 */
export class Client {
    #ai: GoogleGenAI;
    #settings: ClientSettings;

    constructor(settings: ClientSettings) {
        let options: GoogleGenAIOptions;
        switch (settings.api) {
            case 'Gemini':
                options = {
                    apiKey: settings.apiKey,
                };
                break;

            case 'GeminiEnterprise':
                options = {
                    enterprise: true,
                    googleAuthOptions: {
                        credentials: JSON.parse(settings.googleCloud.credentials),
                    },
                    location: settings.googleCloud.location,
                    project: settings.googleCloud.project,
                };
                break;
        }

        this.#ai = new GoogleGenAI(options);
        this.#settings = settings;
    }

    /**
     * Uses the model to generate an image, in accordance with the given |request|. This causes an
     * API call over the internet, and may take an arbitrary amount of time to complete. All content
     * will be read prior to being returned by this method. Exceptions will be caught.
     *
     * @param request The request that should be issued against the API.
     * @return The generated image once all chunks have been received.
     */
    async safeGenerateImage(request: GenerateImageRequest): Promise<ModelImageResponse> {
        try {
            const generatedImage = await this.generateImage(request);
            return {
                success: true,
                ...generatedImage,
            };
        } catch (error: any) {
            return {
                success: false,
                error: error.message,
            };
        }
    }

    /**
     * Uses the model to generate an image, in accordance with the given |request|. This causes an
     * API call over the internet, and may take an arbitrary amount of time to complete. All content
     * will be read prior to being returned by this method.
     *
     * @param request The request that should be issued against the API.
     * @throws Any exception that may be issued by the Google GenAI APIs.
     * @return The generated image once all chunks have been received.
     */
    async generateImage(request: GenerateImageRequest) {
        const stream = await this.generateContentStream(request, {
            model: this.#settings.models.image,
            config: {
                candidateCount: /* fixed= */ 1,
                systemInstruction: request.systemPrompt,
                imageConfig: {
                    aspectRatio: request.aspectRatio,
                },
            },
        });

        let responseId: string | undefined;

        const data: string[] = [ /* no data yet */ ];
        const text: string[] = [ /* no text yet */ ];

        for await (const chunk of stream) {
            responseId = chunk.responseId;

            if (!!chunk.data)
                data.push(chunk.data);
            if (!!chunk.text)
                text.push(chunk.text);
        }

        return {
            responseId,
            data: data.join(''),
            text: text.length ? text.join('') : undefined,
        };
    }

    /**
     * Uses the model to generate text, in accordance with the given |request|. This causes an API
     * call over the internet, and may take an arbitrary amount of time to complete. All content
     * will be read prior to being returned by this method. Exceptions will be caught.
     *
     * @param request The request that should be issued against the API.
     * @return The generated text once all chunks have been received.
     */
    async safeGenerateText(request: GenerateTextRequest): Promise<ModelTextResponse> {
        try {
            const generatedText = await this.generateText(request);
            return {
                success: true,
                ...generatedText,
            };
        } catch (error: any) {
            return {
                success: false,
                error: error.message,
            };
        }
    }

    /**
     * Uses the model to generate text, in accordance with the given |request|. This causes an API
     * call over the internet, and may take an arbitrary amount of time to complete. All content
     * will be read prior to being returned by this method.
     *
     * @param request The request that should be issued against the API.
     * @throws Any exception that may be issued by the Google GenAI APIs.
     * @return The generated text once all chunks have been received.
     */
    async generateText(request: GenerateTextRequest) {
        const stream = this.generateTextStream(request);

        let responseId: string | undefined;
        const text: string[] = [ /* none yet */ ];

        for await (const chunk of stream) {
            responseId = chunk.responseId;

            if (!!chunk.text)
                text.push(chunk.text);
        }

        return {
            responseId,
            text: text.join(''),
        };
    }

    /**
     * Uses the model to generate text, in accordance with the given |request|. This causes an API
     * call over the internet, and may take an arbitrary amount of time to complete. Content will
     * be streamed back to the caller as it becomes available.
     *
     * @param request The request that should be issued against the API.
     * @throws Any exception that may be issued by the Google GenAI APIs.
     * @return An asynchronous generator making generated text available as it's received.
     */
    async* generateTextStream(request: GenerateTextRequest) {
        const complexity = request.complexity ?? 'medium';
        const model = this.#settings.models.text[complexity];

        const stream = await this.generateContentStream(request, {
            model,
            config: {
                candidateCount: /* fixed= */ 1,
                temperature: this.#settings.quality.temperature,
                topP: this.#settings.quality.topP,
                systemInstruction: request.systemPrompt,
                thinkingConfig: {
                    thinkingLevel:
                        this.toGeminiThinkingLevel(
                            request.thinkingLevel
                                ?? this.#settings.quality.thinkingLevel
                                ?? 'medium'),
                },
            },
        });

        for await (const chunk of stream) {
            yield {
                responseId: chunk.responseId,
                text: chunk.text,
            };
        }
    }

    /**
     * Utility method which lists the models that are being advertised by the endpoint we're
     * connected to through Google's Generative AI APIs.
     *
     * @throws Any exception that may be issued by the Google GenAI APIs.
     * @return An array with the names and versions of models advertised by the server.
     */
    async listModels() {
        const models: { name: string; version: string }[] = [ /* none yet */ ];
        for await (const model of await this.#ai.models.list()) {
            models.push({
                name: model.name ?? 'Undefined',
                version: model.version ?? 'default',
            });
        }

        return models;
    }

    /**
     * Private method that actually interacts with the model to generate the requested content. Will
     * inject the system prompt and any attachments into the request. All responses are streamed.
     *
     * @param request The request that should be issued against the API.
     * @param parameters Additional parameters to pass to the model.
     * @throws Any exception that may be issued by the Google GenAI APIs.
     * @return An asynchronous generator making generated content available as it's received.
     */
    private async generateContentStream(
        request: GenerateRequest, parameters: Omit<GenerateContentParameters, 'contents'>)
    {
        const attachments: Part[] = [ /* none yet */ ];
        if (!!request.attachments) {
            for (const attachment of request.attachments) {
                const bytes = await attachment.bytes;
                const encodedBytes = Buffer.from(bytes).toString('base64');

                attachments.push({
                    inlineData: {
                        data: encodedBytes,
                        mimeType: attachment.mimeType,
                    },
                });
            }
        }

        return this.#ai.models.generateContentStream({
            contents: [
                {
                    text: request.prompt,
                },
                ...attachments,
            ],
            ...parameters,
        });
    }

    /**
     * Converts the given `thinkingLevel` to the Gemini API's representation.
     */
    private toGeminiThinkingLevel(thinkingLevel: TextGenerationThinkingLevel): ThinkingLevel {
        switch (thinkingLevel) {
            case 'minimal':
                return ThinkingLevel.MINIMAL;
            case 'low':
                return ThinkingLevel.LOW;
            case 'medium':
                return ThinkingLevel.MEDIUM;
            case 'high':
                return ThinkingLevel.HIGH;
        }
    }
}
