// @ts-nocheck
// biome-ignore-all lint/style/useImportType: not feasible
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class DutyBookTable extends Table<DBConnection, 'DutyBookTable'> {
    dutyBookId = this.autogeneratedPrimaryKey('duty_book_id', 'int');
    dutyBookUserId = this.column('duty_book_user_id', 'int');
    dutyBookEventId = this.column('duty_book_event_id', 'int');
    dutyBookIncident = this.column('duty_book_incident', 'string');
    dutyBookAiSummary = this.optionalColumnWithDefaultValue('duty_book_ai_summary', 'string');
    dutyBookCreated = this.columnWithDefaultValue<ZonedDateTime>('duty_book_created', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    dutyBookUpdated = this.columnWithDefaultValue<ZonedDateTime>('duty_book_updated', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    dutyBookHidden = this.optionalColumnWithDefaultValue<ZonedDateTime>('duty_book_hidden', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    dutyBookDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('duty_book_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('duty_book');
    }
}

export const tDutyBook = new DutyBookTable();

