// @ts-nocheck
// biome-ignore-all lint/style/useImportType: not feasible
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    EventTicketProvider,
    EventAvailabilityStatus,
} from "../Types";

export class EventsTable extends Table<DBConnection, 'EventsTable'> {
    eventId = this.autogeneratedPrimaryKey('event_id', 'int');
    eventName = this.column('event_name', 'string');
    eventShortName = this.column('event_short_name', 'string');
    eventSlug = this.column('event_slug', 'string');
    eventHidden = this.columnWithDefaultValue('event_hidden', 'int');
    eventStartTime = this.column<Temporal.ZonedDateTime>('event_start_time', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    eventEndTime = this.column<Temporal.ZonedDateTime>('event_end_time', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    eventTimingPublished = this.column('event_timing_published', 'int');
    availabilityBuildUp = this.columnWithDefaultValue('availability_build_up', 'int');
    availabilityTearDown = this.columnWithDefaultValue('availability_tear_down', 'int');
    hotelEnabled = this.columnWithDefaultValue('hotel_enabled', 'int');
    hotelInformationPublished = this.columnWithDefaultValue('hotel_information_published', 'int');
    hotelPreferencesStart = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('hotel_preferences_start', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    hotelPreferencesEnd = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('hotel_preferences_end', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    refundEnabled = this.columnWithDefaultValue('refund_enabled', 'int');
    refundInformationPublished = this.columnWithDefaultValue('refund_information_published', 'int');
    refundRequestsStart = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('refund_requests_start', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    refundRequestsEnd = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('refund_requests_end', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    ticketsAutoGrantEnabled = this.columnWithDefaultValue('tickets_auto_grant_enabled', 'int');
    ticketsAutoGrantTicketId = this.optionalColumnWithDefaultValue('tickets_auto_grant_ticket_id', 'string');
    ticketsAutoRevokeEnabled = this.columnWithDefaultValue('tickets_auto_revoke_enabled', 'int');
    ticketsProvider = this.optionalColumnWithDefaultValue<EventTicketProvider>('tickets_provider', 'enum', 'EventTicketProvider');
    trainingEnabled = this.columnWithDefaultValue('training_enabled', 'int');
    trainingInformationPublished = this.columnWithDefaultValue('training_information_published', 'int');
    trainingPreferencesStart = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('training_preferences_start', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    trainingPreferencesEnd = this.optionalColumnWithDefaultValue<Temporal.ZonedDateTime>('training_preferences_end', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    eventAvailabilityStatus = this.column<EventAvailabilityStatus>('event_availability_status', 'enum', 'EventAvailabilityStatus');
    eventLocation = this.optionalColumnWithDefaultValue('event_location', 'string');
    eventTimezone = this.column('event_timezone', 'string');
    eventHotelRoomForm = this.optionalColumnWithDefaultValue('event_hotel_room_form', 'string');
    eventFestivalId = this.optionalColumnWithDefaultValue('event_festival_id', 'int');
    eventIdentityId = this.optionalColumnWithDefaultValue('event_identity_id', 'int');
    //eventYtpId = this.optionalColumnWithDefaultValue('event_ytp_id', 'int');
    eventYtpEventId = this.optionalColumnWithDefaultValue('event_ytp_event_id', 'int');
    eventYtpExternalEventId = this.optionalColumnWithDefaultValue('event_ytp_external_event_id', 'string');
    eventWeeztixGuid = this.optionalColumnWithDefaultValue('event_weeztix_guid', 'string');

    constructor() {
        super('events');
    }
}

export const tEvents = new EventsTable();

