// @ts-nocheck
// biome-ignore-all lint/style/useImportType: not feasible
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    DateType,
} from "../Types";
import {
    PlainDate,
    ZonedDateTime,
} from "../../Temporal";

export class EventsDatesTable extends Table<DBConnection, 'EventsDatesTable'> {
    dateId = this.autogeneratedPrimaryKey('date_id', 'int');
    eventId = this.column('event_id', 'int');
    dateType = this.column<DateType>('date_type', 'enum', 'DateType');
    dateDate = this.column<PlainDate>('date_date', 'customLocalDate', 'date', TemporalTypeAdapter);
    dateOwnerId = this.optionalColumnWithDefaultValue('date_owner_id', 'int');
    dateTitle = this.column('date_title', 'string');
    dateDescription = this.column('date_description', 'string');
    dateCompleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('date_completed', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    dateDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('date_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('events_dates');
    }
}

export const tEventsDates = new EventsDatesTable();

