// @ts-nocheck
// biome-ignore-all lint/style/useImportType: not feasible
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class UsersCommunicationTable extends Table<DBConnection, 'UsersCommunicationTable'> {
    userId = this.column('user_id', 'int');
    userCommunicationId = this.autogeneratedPrimaryKey('user_communication_id', 'int');
    communicationEventId = this.column('communication_event_id', 'int');
    communicationTeamId = this.column('communication_team_id', 'int');
    communicationPromptId = this.column('communication_prompt_id', 'string');
    communicationSenderId = this.column('communication_sender_id', 'int');
    communicationDate = this.column<ZonedDateTime>('communication_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('users_communication');
    }
}

export const tUsersCommunication = new UsersCommunicationTable();

