// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

'use client';

import Link from 'next/link';

import { default as MuiLink } from '@mui/material/Link';
import Tooltip from '@mui/material/Tooltip';
import Typography from '@mui/material/Typography';
import VisibilityIcon from '@mui/icons-material/Visibility';
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';

import { type DataTableColumn, DataTable } from '@app/admin/components/DataTable';
import { LocalDateTime } from '@app/admin/components/LocalDateTime';

/**
 * Props accepted by the <IncidentTable> component.
 */
interface IncidentTableProps {
    /**
     * Whether linking through to the reporter's account should be enabled.
     */
    enableAccountLinks?: boolean;

    /**
     * The list of incidents that should be displayed in the table.
     */
    incidents: {
        /**
         * Unique ID of the incident.
         */
        id: number;

        /**
         * Date at which the incident was reported. In a Temporal ZDT-compatible serialisation.
         */
        date: string;

        /**
         * Summary of the incident, when it's been generated by AI.
         */
        summary?: string;

        /**
         * Text associated with the incident.
         */
        incident: string;

        /**
         * Unique ID of the user who reported the incident.
         */
        userId: number;

        /**
         * Name of the user who reported the incident.
         */
        userName: string;

        /**
         * Whether the incident's details have been hidden from regular volunteers.
         */
        hidden: boolean;

    }[];
}

/**
 * The <IncidentTable> component displays a table with all reported incidents for the current
 * event. Display, by default, roughly matches what's shown in the Volunteer Portal.
 */
export function IncidentTable(props: IncidentTableProps) {
    const columns: DataTableColumn<IncidentTableProps['incidents'][number]>[] = [
        {
            display: 'flex',
            field: 'id',
            width: 50,

            headerAlign: 'center',
            align: 'center',

            renderHeader: () =>
                <Tooltip title="Are the details available?">
                    <VisibilityIcon fontSize="small" color="primary" />
                </Tooltip>,

            renderCell: params => {
                if (params.row.hidden) {
                    return (
                        <Tooltip title="Details have been hidden">
                            <VisibilityOffIcon fontSize="small" color="error" />
                        </Tooltip>
                    );
                } else {
                    return (
                        <Tooltip title="Details are available">
                            <VisibilityIcon fontSize="small" color="success" />
                        </Tooltip>
                    );
                }
            },
        },
        {
            field: 'date',
            headerName: 'Reported on',
            width: 175,

            renderCell: params =>
                <MuiLink component={Link} href={`./duty-book/${params.row.id}`}>
                    <LocalDateTime dateTime={params.value} format="YYYY-MM-DD HH:mm:ss" />
                </MuiLink>,
        },
        {
            field: 'incident',
            headerName: 'Incident',
            flex: 1,

            renderCell: params => {
                if (params.row.summary) {
                    return (
                        <Typography variant="inherit" component="span">
                            {params.row.summary}
                        </Typography>
                    );
                } else {
                    return (
                        <Typography variant="inherit" color="textDisabled" component="span"
                                    sx={{ fontStyle: 'italic' }}>
                            {params.row.incident}
                        </Typography>
                    );
                }
            },
        },
        {
            field: 'userName',
            headerName: 'Reported by',
            width: 200,

            renderCell: params => {
                if (!props.enableAccountLinks)
                    return params.value;

                return (
                    <MuiLink component={Link}
                             href={`/admin/organisation/accounts/${params.row.userId}`}>
                        {params.value}
                    </MuiLink>
                );
            },
        }
    ];

    return (
        <DataTable columns={columns} defaultSort={{ field: 'date', sort: 'desc' }}
                   rows={props.incidents} />
    );
}
