// Copyright 2026 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

import { forbidden, notFound } from 'next/navigation';
import { z } from 'zod/v4';

import { DutyBookSummaryPrompt } from '@lib/ai/prompts/DutyBookSummaryPrompt';
import { SectionIntroduction } from '@app/admin/components/SectionIntroduction';
import { Section } from '@app/admin/components/Section';
import { SummaryAction } from './SummaryAction';
import { VisibilityHeaderCell, VisibilityCell } from './VisibilityCell';
import { createAiClient } from '@lib/integrations/genai';
import { DataTable, createDataSource, withContext, withRowModel, type Column, type ExtractRowModel } from '@app/admin/components/DataTable';
import { executeAccessCheck } from '@lib/auth/AuthenticationContext';
import { executeServerAction } from '@lib/serverAction';
import { formatDate } from '@lib/Temporal';
import { generateEventMetadataFn } from '../../generateEventMetadataFn';
import { readSetting } from '@lib/Settings';
import { verifyAccessAndFetchPageInfo } from '@app/admin/events/verifyAccessAndFetchPageInfo';
import db, { tDutyBook, tEvents, tTeams, tUsers } from '@lib/database';

/**
 * Zod type that describes that no data is expected for a Server Action.
 */
const kNoDataRequired = z.object({ /* no parameters */ });

/**
 * Server action that will be called when an administrator requests a summary of the Duty Book to
 * be generated. We don't provide guarantees towards the stability of these summaries.
 */
async function generateSummary(event: string, team: string) {
    'use server';
    return executeServerAction(new FormData, kNoDataRequired, async (data, props) => {
        if (!props.access.can('event.duty-book', 'read', { event, team }))
            forbidden();

        const dutyBookJoin = tDutyBook.forUseInLeftJoin();

        const dutyBookContents = await db.selectFrom(tEvents)
            .innerJoin(tTeams)
                .on(tTeams.teamSlug.equals(team))
            .leftJoin(dutyBookJoin)
                .on(dutyBookJoin.dutyBookEventId.equals(tEvents.eventId))
                    .and(dutyBookJoin.dutyBookDeleted.isNull())
            .where(tEvents.eventSlug.equals(event))
            .select({
                event: tEvents.eventName,
                team: tTeams.teamName,
                incidents: db.aggregateAsArray({
                    date: dutyBookJoin.dutyBookCreated,
                    incident: dutyBookJoin.dutyBookIncident,
                })
            })
            .groupBy(tEvents.eventId, tTeams.teamId)
            .executeSelectNoneOrOne();

        if (!dutyBookContents || !dutyBookContents?.incidents.length)
            return { success: false, error: 'The Duty Book is empty, nothing to summarise.' };

        dutyBookContents.incidents.sort((lhs, rhs) =>
            lhs.date.epochMilliseconds - rhs.date.epochMilliseconds);

        const input: string[] = [ /* none yet */ ];
        for (const { date, incident } of dutyBookContents.incidents)
            input.push(`[${formatDate(date, 'dddd [at] HH:mm')}]: ${incident}`);

        const promptInstance = new DutyBookSummaryPrompt();
        const prompt = await promptInstance.evaluate({
            event: dutyBookContents.event,
            input: JSON.stringify(input),
            team: dutyBookContents.team,
        });

        const client = await createAiClient();
        const summary = await client.safeGenerateText({ prompt });

        if (!summary.success)
            return { success: false, error: summary.error };

        return {
            success: true,
            summary: summary.text,
        };
    });
}

/**
 * Data source through which the Duty Book incidents can be retrieved.
 */
const dutyBookDataSource = createDataSource('event/team/duty-book', withContext({
    /**
     * Unique ID of the event to display the duty book for.
     */
    eventId: z.number(),

    /**
     * Slug of the event to display the duty book for.
     */
    eventSlug: z.string(),

    /**
     * Slug of the team to display the duty book for.
     */
    teamSlug: z.string(),

}), withRowModel({
    /**
     * Unique ID of the incident.
     */
    id: z.number(),

    /**
     * Date at which the incident was reported.
     */
    date: z.string(),

    /**
     * Summary of the incident, when it's been generated by AI.
     */
    summary: z.string().optional(),

    /**
     * The user who reported the incident.
     */
    user: z.object({
        id: z.number(),
        name: z.string(),
    }),

    /**
     * Whether the incident's details have been hidden.
     */
    hidden: z.boolean(),

}), {
    async authorize(operation, props, context) {
        executeAccessCheck(props.authenticationContext, {
            check: 'admin',
            permission: {
                permission: 'event.duty-book',
                operation: 'read',
                scope: {
                    event: context.eventSlug,
                    team: context.teamSlug,
                },
            },
        });
    },

    async list(params, props, context) {
        const dbInstance = db;
        const results = await dbInstance.selectFrom(tDutyBook)
            .innerJoin(tUsers)
                .on(tUsers.userId.equals(tDutyBook.dutyBookUserId))
            .where(tDutyBook.dutyBookEventId.equals(context.eventId))
                .and(tDutyBook.dutyBookDeleted.isNull())
                .and(tUsers.name.containsInsensitiveIfValue(params.search).or(
                    tDutyBook.dutyBookIncident.containsInsensitiveIfValue(params.search).or(
                    tDutyBook.dutyBookAiSummary.containsInsensitiveIfValue(params.search)
                )))
            .select({
                id: tDutyBook.dutyBookId,
                date: dbInstance.dateTimeAsString(tDutyBook.dutyBookCreated),
                summary: tDutyBook.dutyBookAiSummary,
                user: {
                    id: tUsers.userId,
                    name: tUsers.name,
                },
                hidden: tDutyBook.dutyBookHidden.isNotNull(),
            })
            .orderBy(params.sort.field === 'user' ? 'user.name' : 'date', params.sort.direction)
            .limit(params.page.limit)
                .offset(params.page.offset)
            .executeSelectPage();

        return {
            rowCount: results.count,
            rows: results.data,
        };
    },
});

/**
 * Export the row model for use in the child components used by the data table.
 */
export type DutyBookRowModel = ExtractRowModel<typeof dutyBookDataSource>;

/**
 * The Duty Book is the place where volunteers log information about incidents that happens during
 * the festival, so that others are aware of the specifics and/or the associated pictures.
 */
export default async function EventTeamDutyBookPage(
    props: PageProps<'/admin/events/[event]/[team]/duty-book'>)
{
    const params = await props.params;

    const { event, team } = await verifyAccessAndFetchPageInfo(props.params, {
        permission: 'event.duty-book',
        operation: 'read',
        scope: {
            event: params.event,
            team: params.team,
        },
    });

    const columns: Column<DutyBookRowModel>[] = [
        {
            display: 'flex',
            field: 'id',
            width: 50,
            sortable: false,

            headerAlign: 'center',
            align: 'center',

            template: 'component',
            templateProps: {
                headerComponent: VisibilityHeaderCell,
                component: VisibilityCell,
            },
        },
        {
            field: 'date',
            headerName: 'Reported on',
            width: 185,

            template: 'date',
            templateProps: {
                format: 'YYYY-MM-DD HH:mm:ss',
                href: './duty-book/{id}',
            },
        },
        {
            field: 'summary',
            headerName: 'Incident',
            sortable: false,
            flex: 1,

            template: 'text',
            templateProps: {
                defaultValue: 'Summary missing…',
            },
        },
        {
            field: 'user',
            headerName: 'Reported by',
            width: 200,

            template: 'account',
        }
    ];

    const dutyBookEnabled = await readSetting('schedule-duty-book');
    if (!dutyBookEnabled || !team.flagEnableDutyBook)
        notFound();

    const generateSummaryFn = generateSummary.bind(null, event.slug, team.slug);

    return (
        <Section title="Duty book" subtitle={event.shortName}
                 headerAction={ <SummaryAction generateSummaryFn={generateSummaryFn} /> }>
            <SectionIntroduction>
                The duty book lists all reported incidents during this festival. The information
                can be consumed in the portal as well.
            </SectionIntroduction>
            <DataTable columns={columns} source={dutyBookDataSource}
                       context={{ eventId: event.id, eventSlug: event.slug, teamSlug: team.slug }}
                       defaultSort={{ field: 'date', sort: 'desc' }}
                       listViewProps={{
                           primaryField: 'user.name',
                           secondaryField: 'summary',
                           dateField: 'date',
                           dateFieldFormat: 'ddd, HH:mm',
                           startComponent: VisibilityCell,
                           linkTemplate: './duty-book/{id}',
                       }} />
        </Section>
    );
}

export const generateMetadata = generateEventMetadataFn('Duty book');
