name: Deploy Volunteer Manager

on: [ workflow_dispatch ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the manager to production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        command_timeout: 20m
        script: |
          cd ~/volunteer-manager
          git reset --hard
          git pull --rebase
          npm install --force
          npm run-script test
          npm run-script build-prod
          docker system prune -f
          docker stop volunteer-manager-docker
          docker rm volunteer-manager-docker
          docker run -d --name volunteer-manager-docker --restart always -p 3001:3001 volunteer-manager-docker:latest
