name: Restart Volunteer Manager

on: [ workflow_dispatch ]

jobs:
  deploy:
    name: Restart
    runs-on: ubuntu-latest
    steps:
    - name: Restart the manager in production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        command_timeout: 10m
        script: |
          cd ~/volunteer-manager
          docker restart volunteer-manager-docker
