name: Restart Volunteer Manager (Staging)

on: [ workflow_dispatch ]

jobs:
  deploy:
    name: Restart
    runs-on: ubuntu-latest
    steps:
    - name: Restart the manager in production
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST_STAGING }}
        port: ${{ secrets.PORT_STAGING }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        command_timeout: 10m
        script: |
          cd ~/volunteer-manager-staging
          docker restart volunteer-manager-staging
